version: "3.7"
name: scheduled-tweets-app

services:
  db:
    image: postgres
    restart: always
    container_name: demo-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: 
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  ruby_dev:
    build: .
    container_name: ror-app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
    environment:
      REDIS_URL: redis://redis-server:6379
      RAILS_ENV: ${RAILS_ENV}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - redis-server
      - db

  redis-server:
    image: redis
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    volumes: 
      - cache:/data
      
volumes:
  postgres_data: {}
  app-storage: {}
  cache:
    driver: local